### ISSUE TITLE
[BUG] Latest publish broke my code by changing the API of interpolateNumber without bumping the major version

### ISSUE THREAD

**Issue by allain** [okikio/spring-easing#4]
**Describe the bug**
interpolateNumber API has changed

From: `export function interpolateNumber (t: number, values: number[], decimal = 3) {`
To:   `export function interpolateNumber(frames: number[], values: number[], decimal = 3) {`

**To Reproduce**

1. Run an app that still uses the old API

**Expected behavior**
Without a major version bump I expect interpolateNumber to not have a breaking change. I see the idea was to batch interpolate numbers.

If that's the case I think adding a new method `interpolateNumbers` implement the new behaviour and possibly having the old function call out to it.

**Comment by okikio** [comment]
Yeah, I'm starting to realize that I should have made it a breaking change, sorry about that. I'll keep the change but introduce a new utility function that will allow the use of the old syntax, what do you think about that solution. 

E.g. `mapToFrames(interpolateColor)`, does that work?

Also, please let me know how it works for you and if there are anythings you'd like improved.

**Comment by okikio** [comment]
@allain I've re-added the instantaneous interpolation functions of yore (under a new name, `instantNumber`, `intantString`, etc...), in the latest release, please let me know what you think?

**Comment by allain** [comment]
Hey. I don't think this is an improvement. Unless I'm misunderstanding things the intent of the function is now unclear.

Originally there was interpolateX which interpolated a single X, and the function did exactly what it was named.

Now we have interpolateX which interpolates many Xs (unclear)
and a new function instantX which interpolates a single X.

I think the clearest thing would be to name them:

interpolateX => interpolates a single X
interpolateXs => interpolates a batch of Xs

Without breaking the API further, I'm not sure how to move forward.

**Comment by allain** [comment]
Certainly nothing wrong with optimizing. Maybe just aim to keep the API that's in use static.

**Comment by okikio** [comment]
I'll probably create a variant of SpringEasing specifically just for batching, e.g. SpringEasingOptimized

**Comment by okikio** [comment]
Done
